Add configurations for retaining select query string parameters in resources and http.url
DataDog/dd-trace-php pull request #1566
Opened 2022-04-11 17:23 UTC by bwoebi

### Description

This restores the possibility to fully send the request URL as http.url. (Which was previously disabled to prevent accidental PII leaks.)
Additionally query parameters in resources are now supported.

This is configurable via `datadog.trace.http_url_query_param_whitelist` (for http.url) and `datadog.trace.resource_uri_query_param_whitelist` (for resources).

Fixes #1270, #1033, #1117.

### Readiness checklist
- [x] (only for Members) Changelog has been added to the release document.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

2022-04-12 13:40 UTC, krakjoe submitted a review, later dismissed

2022-04-12 14:02 UTC, labbati requested changes

2022-04-26 17:16 UTC, krakjoe approved these changes
re-ack

2022-04-27 09:24 UTC, labbati approved these changes

2022-04-27 09:24 UTC, merged