Add B3 headers injection and extraction
DataDog/dd-trace-php pull request #1629
Opened 2022-06-28 10:52 UTC by bwoebi

### Description

Support for B3 headers.

### Readiness checklist
- [x] (only for Members) Changelog has been added to the release document.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

2022-06-29 16:04 UTC, labbati requested changes
Thanks @bwoebi for the work on B3 headers, I added a few comments or request for clarification.

2022-06-29 16:14 UTC, bwoebi commented on ext/php7/handlers_curl.c
> +            add_next_index_str(&headers, zend_strpprintf(0, "b3: %s", b3_sampling_decision));
```
A deny decision encodes as:

b3: 0
```
from https://github.com/openzipkin/b3-propagation#single-header

2022-06-29 16:15 UTC, bwoebi commented
Thanks for the review, I'll apply the suggestions soon.

2022-07-01 14:00 UTC, labbati commented on ext/php7/ddtrace.c
> +    if (parse_datadog && zai_read_header_literal("X_DATADOG_ORIGIN", &DDTRACE_G(dd_origin)) == ZAI_HEADER_SUCCESS) {
@bwoebi please remove `parse_datadog` or convince me of the opposite 😄

2022-07-01 14:09 UTC, labbati approved these changes
Thanks for the work on this!

2022-07-01 14:10 UTC, merged